# Generated by Django 4.0.5 on 2022-06-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imgupload_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgupload',
            old_name='date',
            new_name='added_at',
        ),
    ]
