# Generated by Django 4.0.5 on 2022-06-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_imgupload_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgupload',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imgupload',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
