# Generated by Django 4.0.5 on 2022-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imgupload_name_alter_imgupload_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='name',
            field=models.CharField(blank=True, choices=[(1, 'orginal'), (2, '200px'), (3, '400px')], max_length=255, null=True),
        ),
    ]
