# Generated by Django 4.0.5 on 2022-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_imgupload_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgupload',
            name='name',
        ),
        migrations.AddField(
            model_name='imgupload',
            name='image_type',
            field=models.CharField(blank=True, choices=[(1, 'original'), (2, '200px'), (3, '400px')], default=1, max_length=255, null=True),
        ),
    ]
