# Generated by Django 4.0.5 on 2022-06-12 19:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_imgupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.image_file_path),
        ),
    ]
