# Generated by Django 4.0.5 on 2022-06-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_imgupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgupload',
            name='original_image_id',
            field=models.IntegerField(default=None),
        ),
    ]
