# Generated by Django 4.0.5 on 2022-06-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_imgupload_original_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgupload',
            name='original_image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
