# Generated by Django 4.0.5 on 2022-06-14 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_timegenerateimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timegenerateimg',
            name='time_of_expiry',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
